# Generated by Django 2.1.5 on 2021-01-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
